sudo: false
language: rust
addons:
  apt:
    sources:
      - kalakris-cmake
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake
rust:
  - nightly
addons:
  postgresql: '9.4'
before_script:
  - pip install 'travis-cargo<0.2' --user
  - export PATH=$HOME/.local/bin:$PATH
  - export PATH=$PATH:/home/travis/.cargo/bin
  - psql -c 'create database giistr;' -U postgres
  - cargo install diesel_cli
  - diesel migration run
script:
  - cargo build
  - cargo build --release
env:
  global:
    - TRAVIS_CARGO_NIGHTLY_FEATURE=""
    - DATABASE_URL=postgres://postgres@localhost/giistr
    - VCAP_SERVICES=postgres://postgres@localhost/giistr