sudo: false
language: rust
addons:
  apt:
    sources:
      - kalakris-cmake
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake
rust:
  - nightly
addons:
  postgresql: '9.4'
before_script:
  - pip install 'travis-cargo<0.2' --user
  - export PATH=$HOME/.local/bin:$PATH
  - psql -c 'create database giistr;' -U postgres
  - cargo install diesel_cli
  - diesel migration run
script:
  - cargo build
env:
  global:
    - TRAVIS_CARGO_NIGHTLY_FEATURE=""
    - DATABASE_URL=postgres://postgres@localhost/giistr
    - GIISTR_DATABASE_URL=postgres://postgres@localhost/giistr