sudo: false
language: rust
addons:
  apt:
    sources:
    - kalakris-cmake
    packages:
    - libcurl4-openssl-dev
    - libelf-dev
    - libdw-dev
    - cmake
  postgresql: '9.4'
rust:
- nightly
before_script:
- pip install 'travis-cargo<0.2' --user
- export PATH=$HOME/.local/bin:$PATH
- export PATH=$PATH:/home/travis/.cargo/bin
- psql -c 'create database giistr;' -U postgres
- cargo install diesel_cli
- diesel migration run
script:
- cargo build -j8
- cargo build --release -j8
env:
  global:
  - TRAVIS_CARGO_NIGHTLY_FEATURE=""
  - DATABASE_URL=postgres://postgres@localhost/giistr
  - GIISTR_DATABASE_URL=postgres://postgres@localhost/giistr
deploy:
  provider: cloudfoundry
  api: https://api.ng.bluemix.net
  username: alexr.3165@gmail.com
  password:
    secure: I/usc5JEmxBggUh2gu0S1oAkeKAVZx39FWHjgObzkLYRHEHgeB7HEACjGeecBwFKBWqRZRGgg4aYxc5yueHr3pd8SkZglUbItSdwuR07gZ++oTfo44LmDyqjAllrOy72RN3eYbQZlMFrO/yG8WYjEyx64jL4ofH00oLI51qDI7gw0pYBMj4o0ApDlkQYevhpF1Cz12pw1N7cZnxEZ55Igg1lZXw/ybCut3cdMA7R2kK2cmvOqs4ru+ETW9ugVpW//Rht7XA/Z8Cdb+eIDgmkwiJDvKpx1p3U9AEwVZTYBcAVNc1VNoW7JLA/xy+MLjlYC2EbDfB08zLn3fBaKg9lyRa5qfy/NVaaeRMOoPxI354KIzCv+BNLUMHYGP09F2ynt8NCXpAf1coxbJ4WA2Rq93+Htc65l/oVzCd9rSHr9/M+2CWK7+so7CpBZpCRZKa1+dQFjVQDRIPUTOyN1i5QXwN4pFnbZsZLE6HutluYhH4d/Nb6VMcBNvu/COhJF4DJesGicHGVU08F6lmaFN4i3k9PCb03MaygAAzM4sGNeesS6MQY3zk7TszCpbQzTHZiXq8fuMJ/v/peIGjRW2NN4SAE+TgBd0pIMKkBopcsoCvWWWRMnKsVOLSabZGCkA5gWue06854bvdWpSISTiWYWOkqsYV8raUbCve9itI1j6s=
  organization: numeractive
  space: giistr
  on:
    repo: giistr/giistr_api
