CREATE TABLE users (
  id TEXT NOT NULL PRIMARY KEY,
  created_at INTEGER DEFAULT CURRENT_TIMESTAMP,
  updated_at INTEGER DEFAULT CURRENT_TIMESTAMP,

  token_id TEXT NOT NULL,
  github_user_id TEXT NOT NULL
)
