CREATE TABLE users (
  id VARCHAR(36) NOT NULL PRIMARY KEY,
  created_at INT DEFAULT CURRENT_TIMESTAMP,
  updated_at INT DEFAULT CURRENT_TIMESTAMP,

  token_id VARCHAR(256) NOT NULL,
  github_user_id VARCHAR(256) NOT NULL
)
